export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USERNAME_RESETTED = "USERNAME_RESETTED";

export const FETCH_BASIC_INFO = "FETCH_BASIC_INFO";
export const UPDATE_BASIC_INFO = "UPDATE_BASIC_INFO";

export const FETCH_SCHOOL_INFO = "FETCH_SCHOOL_INFO";
export const UPDATE_SCHOOL_INFO = "UPDATE_SCHOOL_INFO";

export const FETCH_AFTER_NAVODAYA_INFO = "FETCH_AFTER_NAVODAYA_INFO";
export const UPDATE_AFTER_NAVODAYA_INFO = "UPDATE_AFTER_NAVODAYA_INFO";

export const FETCH_SOCIAL_ACC_INFO = "FETCH_SOCIAL_ACC_INFO";
export const UPDATE_SOCIAL_ACC_INFO = "UPDATE_SOCIAL_ACC_INFO";

export const FETCH_FAVOURITES_INFO = "FETCH_FAVOURITES_INFO";
export const UPDATE_FAVOURITES_INFO = "UPDATE_FAVOURITES_INFO";

export const FETCH_FIRST_THINGS_INFO = "FETCH_FIRST_THINGS_INFO";
export const UPDATE_FIRST_THINGS_INFO = "UPDATE_FIRST_THINGS_INFO";

export const LOCATION_COUNTRIES_FETCHED = "LOCATION_COUNTRIES_FETCHED";
export const LOCATION_STATES_FETCHED = "LOCATION_STATES_FETCHED";
export const LOCATION_CITIES_FETCHED = "LOCATION_CITIES_FETCHED";
export const CLEAR_CITIES = "CLEAR_CITIES";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const FETCH_ANNOUNCEMENTS = "FETCH_ANNOUNCEMENTS";
