export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const FETCH_BASIC_INFO = "FETCH_BASIC_INFO";
export const UPDATE_BASIC_INFO = "UPDATE_BASIC_INFO";

export const FETCH_SCHOOL_INFO = "FETCH_SCHOOL_INFO";
export const UPDATE_SCHOOL_INFO = "UPDATE_SCHOOL_INFO";

export const FETCH_AFTER_NAVODAYA_INFO = "FETCH_AFTER_NAVODAYA_INFO";
export const UPDATE_AFTER_NAVODAYA_INFO = "UPDATE_AFTER_NAVODAYA_INFO";

export const FETCH_SOCIAL_ACC_INFO = "FETCH_SOCIAL_ACC_INFO";
export const FETCH_FAVOURITES_INFO = "FETCH_FAVOURITES_INFO";
export const FETCH_FIRST_THINGS_INFO = "FETCH_FIRST_THINGS_INFO";